// GENERATED by scripts/gen-bpmn-icons.mjs — do not edit by hand.
//
// A small, always-available icon pack (the `bpmn` package for `icon:bpmn:<name>`).
// The task-type glyphs (and the activity `loop` marker) are borrowed from Material
// Design Icons (Pictogrammers), licensed under Apache-2.0 — see licenses/mdi-APACHE-2.0.txt
// and THIRD-PARTY-NOTICES.md. The gateway markers (exclusive/inclusive/parallel/event)
// and the multi-instance markers (mi-sequential/mi-parallel) are hand-drawn here (MIT).
// The `manual` glyph is rotated 90° clockwise. Regenerate with:
// node scripts/gen-bpmn-icons.mjs
import type { IconifyJSON } from '@iconify/types';

export const BPMN_PACK = 'bpmn';

export const bpmnIcons: IconifyJSON = {
  "prefix": "bpmn",
  "width": 24,
  "height": 24,
  "icons": {
    "receive": {
      "body": "<path fill=\"currentColor\" d=\"M22 6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2zm-2 0l-8 5l-8-5zm0 12H4V8l8 5l8-5z\"/>"
    },
    "send": {
      "body": "<path fill=\"currentColor\" d=\"m20 8l-8 5l-8-5V6l8 5l8-5m0-2H4c-1.11 0-2 .89-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2\"/>"
    },
    "script": {
      "body": "<path fill=\"currentColor\" d=\"M15 20a1 1 0 0 0 1-1V4H8a1 1 0 0 0-1 1v11H5V5a3 3 0 0 1 3-3h11a3 3 0 0 1 3 3v1h-2V5a1 1 0 0 0-1-1a1 1 0 0 0-1 1v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3v-1h11a2 2 0 0 0 2 2M9 6h5v2H9zm0 4h5v2H9zm0 4h5v2H9z\"/>"
    },
    "manual": {
      "body": "<path fill=\"currentColor\" d=\"M3 16c0 4.42 3.58 8 8 8c3.43 0 6.5-2.09 7.77-5.27l2.56-6.43c.25-.64.23-1.38-.15-1.95A2 2 0 0 0 19 9.5l-.78.23c-.46.12-.88.35-1.22.66V4.5A2.5 2.5 0 0 0 14.5 2c-.19 0-.37 0-.54.06A2.5 2.5 0 0 0 11.5 0c-1.06 0-1.96.66-2.33 1.59A2.5 2.5 0 0 0 6 4v.55c-.16-.05-.33-.05-.5-.05A2.5 2.5 0 0 0 3 7zm2-9c0-.28.22-.5.5-.5s.5.22.5.5v5h2V4c0-.28.22-.5.5-.5s.5.22.5.5v8h2V2.5c0-.28.22-.5.5-.5s.5.22.5.5V12h2V4.5c0-.28.22-.5.5-.5s.5.22.5.5V15h2l1-2.5c.15-.45.5-.79 1-.91l.5-.14L16.91 18c-.96 2.41-3.3 4-5.91 4c-3.31 0-6-2.69-6-6z\"/>",
      "rotate": 1
    },
    "service": {
      "body": "<path fill=\"currentColor\" d=\"M12 8a4 4 0 0 1 4 4a4 4 0 0 1-4 4a4 4 0 0 1-4-4a4 4 0 0 1 4-4m0 2a2 2 0 0 0-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2a2 2 0 0 0-2-2m-2 12c-.25 0-.46-.18-.5-.42l-.37-2.65c-.63-.25-1.17-.59-1.69-.99l-2.49 1.01c-.22.08-.49 0-.61-.22l-2-3.46a.493.493 0 0 1 .12-.64l2.11-1.66L4.5 12l.07-1l-2.11-1.63a.493.493 0 0 1-.12-.64l2-3.46c.12-.22.39-.31.61-.22l2.49 1c.52-.39 1.06-.73 1.69-.98l.37-2.65c.04-.24.25-.42.5-.42h4c.25 0 .46.18.5.42l.37 2.65c.63.25 1.17.59 1.69.98l2.49-1c.22-.09.49 0 .61.22l2 3.46c.13.22.07.49-.12.64L19.43 11l.07 1l-.07 1l2.11 1.63c.19.15.25.42.12.64l-2 3.46c-.12.22-.39.31-.61.22l-2.49-1c-.52.39-1.06.73-1.69.98l-.37 2.65c-.04.24-.25.42-.5.42zm1.25-18l-.37 2.61c-1.2.25-2.26.89-3.03 1.78L5.44 7.35l-.75 1.3L6.8 10.2a5.55 5.55 0 0 0 0 3.6l-2.12 1.56l.75 1.3l2.43-1.04c.77.88 1.82 1.52 3.01 1.76l.37 2.62h1.52l.37-2.61c1.19-.25 2.24-.89 3.01-1.77l2.43 1.04l.75-1.3l-2.12-1.55c.4-1.17.4-2.44 0-3.61l2.11-1.55l-.75-1.3l-2.41 1.04a5.42 5.42 0 0 0-3.03-1.77L12.75 4z\"/>"
    },
    "user": {
      "body": "<path fill=\"currentColor\" d=\"M12 4a4 4 0 0 1 4 4a4 4 0 0 1-4 4a4 4 0 0 1-4-4a4 4 0 0 1 4-4m0 2a2 2 0 0 0-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2a2 2 0 0 0-2-2m0 7c2.67 0 8 1.33 8 4v3H4v-3c0-2.67 5.33-4 8-4m0 1.9c-2.97 0-6.1 1.46-6.1 2.1v1.1h12.2V17c0-.64-3.13-2.1-6.1-2.1\"/>"
    },
    "rule": {
      "body": "<path fill=\"currentColor\" d=\"M3 5v14h17V5zm4 2v2H5V7zm-2 6v-2h2v2zm0 2h2v2H5zm13 2H9v-2h9zm0-4H9v-2h9zm0-4H9V7h9z\"/>"
    },
    "loop": {
      "body": "<path fill=\"currentColor\" d=\"M17.65 6.35A7.96 7.96 0 0 0 12 4a8 8 0 0 0-8 8a8 8 0 0 0 8 8c3.73 0 6.84-2.55 7.73-6h-2.08A5.99 5.99 0 0 1 12 18a6 6 0 0 1-6-6a6 6 0 0 1 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4z\"/>",
      "hFlip": true
    },
    "message-in": {
      "body": "<path fill=\"currentColor\" d=\"M22 6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2zm-2 0l-8 5l-8-5zm0 12H4V8l8 5l8-5z\"/>"
    },
    "message-out": {
      "body": "<path fill=\"currentColor\" d=\"m20 8l-8 5l-8-5V6l8 5l8-5m0-2H4c-1.11 0-2 .89-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2\"/>"
    },
    "conditional-in": {
      "body": "<path fill=\"currentColor\" d=\"M3 5v14h17V5zm4 2v2H5V7zm-2 6v-2h2v2zm0 2h2v2H5zm13 2H9v-2h9zm0-4H9v-2h9zm0-4H9V7h9z\"/>"
    },
    "conditional-out": {
      "body": "<path fill=\"currentColor\" d=\"M9 5v4h12V5M9 19h12v-4H9m0-1h12v-4H9M4 9h4V5H4m0 14h4v-4H4m0-1h4v-4H4z\"/>"
    },
    "timer-in": {
      "body": "<path fill=\"currentColor\" d=\"M12 20c4.4 0 8-3.6 8-8s-3.6-8-8-8s-8 3.6-8 8s3.6 8 8 8m0-18c5.5 0 10 4.5 10 10s-4.5 10-10 10S2 17.5 2 12S6.5 2 12 2m5 11.9l-.7 1.3l-5.3-2.9V7h1.5v4.4z\"/>"
    },
    "timer-out": {
      "body": "<path fill=\"currentColor\" d=\"M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10s10-4.5 10-10S17.5 2 12 2m4.3 13.2L11 12.3V7h1.5v4.4l4.5 2.5z\"/>"
    },
    "link-in": {
      "body": "<path fill=\"currentColor\" d=\"M11 16H3V8h8V2l10 10l-10 10zm2-9v3H5v4h8v3l5-5z\"/>"
    },
    "link-out": {
      "body": "<path fill=\"currentColor\" d=\"M4 15V9h8V4.16L19.84 12L12 19.84V15z\"/>"
    },
    "error-in": {
      "body": "<path fill=\"currentColor\" d=\"M7 2h10l-3.5 7H17l-7 13v-8H7zm2 2v8h3v2.66L14 11h-3.76l3.52-7z\"/>"
    },
    "error-out": {
      "body": "<path fill=\"currentColor\" d=\"M7 2v11h3v9l7-12h-4l4-8z\"/>"
    },
    "compensation-in": {
      "body": "<path fill=\"currentColor\" d=\"M10 9.9L7 12l3 2.1zm9 0L16 12l3 2.1zM12 6v12l-8.5-6zm9 0v12l-8.5-6z\"/>"
    },
    "compensation-out": {
      "body": "<path fill=\"currentColor\" d=\"m11.5 12l8.5 6V6m-9 12V6l-8.5 6z\"/>"
    },
    "exclusive": {
      "body": "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"4\" stroke-linecap=\"round\" d=\"M3 3l18 18M21 3L3 21\"/>"
    },
    "inclusive": {
      "body": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"4\"/>"
    },
    "parallel": {
      "body": "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"4\" stroke-linecap=\"round\" d=\"M12 2v20M2 12h20\"/>"
    },
    "event": {
      "body": "<circle cx=\"12\" cy=\"12\" r=\"11.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\"/><circle cx=\"12\" cy=\"12\" r=\"9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\"/><polygon points=\"12,5 18.7,9.8 16.1,17.7 7.9,17.7 5.3,9.8\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linejoin=\"round\"/>"
    },
    "signal-in": {
      "body": "<polygon points=\"12,2 22,21 2,21\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.25\" stroke-linejoin=\"round\"/>"
    },
    "signal-out": {
      "body": "<polygon points=\"12,2 22,21 2,21\" fill=\"currentColor\"/>"
    },
    "escalation-in": {
      "body": "<polygon points=\"12,2 22,21 12,15 2,21\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.25\" stroke-linejoin=\"round\"/>"
    },
    "escalation-out": {
      "body": "<polygon points=\"12,2 22,21 12,15 2,21\" fill=\"currentColor\"/>"
    },
    "multiple-in": {
      "body": "<polygon points=\"12,2 21.5,8.9 17.9,20.1 6.1,20.1 2.5,8.9\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.25\" stroke-linejoin=\"round\"/>"
    },
    "multiple-out": {
      "body": "<polygon points=\"12,2 21.5,8.9 17.9,20.1 6.1,20.1 2.5,8.9\" fill=\"currentColor\"/>"
    },
    "parallel-in": {
      "body": "<polygon points=\"9.5,2 14.5,2 14.5,9.5 22,9.5 22,14.5 14.5,14.5 14.5,22 9.5,22 9.5,14.5 2,14.5 2,9.5 9.5,9.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.25\" stroke-linejoin=\"round\"/>"
    },
    "parallel-out": {
      "body": "<polygon points=\"9.5,2 14.5,2 14.5,9.5 22,9.5 22,14.5 14.5,14.5 14.5,22 9.5,22 9.5,14.5 2,14.5 2,9.5 9.5,9.5\" fill=\"currentColor\"/>"
    },
    "cancel-in": {
      "body": "<polygon points=\"9.5,2 14.5,2 14.5,9.5 22,9.5 22,14.5 14.5,14.5 14.5,22 9.5,22 9.5,14.5 2,14.5 2,9.5 9.5,9.5\" transform=\"rotate(45 12 12)\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.25\" stroke-linejoin=\"round\"/>"
    },
    "cancel-out": {
      "body": "<polygon points=\"9.5,2 14.5,2 14.5,9.5 22,9.5 22,14.5 14.5,14.5 14.5,22 9.5,22 9.5,14.5 2,14.5 2,9.5 9.5,9.5\" transform=\"rotate(45 12 12)\" fill=\"currentColor\"/>"
    },
    "termination-out": {
      "body": "<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"currentColor\"/>"
    },
    "mi-sequential": {
      "body": "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" d=\"M4 6h16M4 12h16M4 18h16\"/>"
    },
    "mi-parallel": {
      "body": "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" d=\"M6 4v16M12 4v16M18 4v16\"/>"
    },
    "adhoc": {
      "body": "<path fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" d=\"M4 12q4 -7 8 0t8 0\"/>"
    },
    "composite": {
      "body": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"1\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><path d=\"M12 7v10M7 12h10\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>"
    }
  }
};
